# Generated by Django 4.1.7 on 2025-04-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_payment_currency_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='eur', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
