apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: agriroute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.6.0 
        ports:
        - containerPort: 9092
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        envFrom:
        - configMapRef:
            name: kafka-env
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 20
          periodSeconds: 20
          failureThreshold: 5
      nodeSelector:
        kubernetes.io/hostname: kub13
      volumes:
      - name: kafka-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: agriroute
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-env
  namespace: agriroute
data:
  apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-env
  namespace: agriroute
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.agriroute.svc.cluster.local:9092"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_CFG_LOG_DIRS: "/bitnami/kafka/data"
  KAFKA_CFG_LOG_RETENTION_BYTES: "1073741824"
  KAFKA_CFG_MESSAGE_MAX_BYTES: "1000000"
  KAFKA_CFG_REPLICA_FETCH_MAX_WAIT_MS: "500"
  KAFKA_CFG_NUM_PARTITIONS: "1"