FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN apt-get update

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app
COPY app/policies.json ./app/policies.json

CMD ["python", "-u", "app/consumer.py"]
