services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - all
    
  api:
    build: .  # 🔹 This tells Docker how to build the API service
    container_name: fastapi_service
    ports:
      - "8080:8080"
    depends_on:
      postgresql: 
        condition: service_healthy
    networks:
      - all
    volumes:
      - .:/app  
      
volumes:
  postgres_data:

networks:
  all:
    driver: bridge
