apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: agriroute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: registry.deti/api-service:latest
          ports:
            - containerPort: 8009
          envFrom:
            - secretRef:
                name: apiservice-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: agriroute
spec:
  selector:
    app: api-service
  ports:
    - port: 8009         
      targetPort: 8009
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notifications
  namespace: agriroute
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  
  selector:
    app: postgres-notifications
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-notifications
  namespace: agriroute
spec:
  serviceName: postgres-notifications
  replicas: 1
  selector:
    matchLabels:
      app: postgres-notifications
  template:
    metadata:
      labels:
        app: postgres-notifications
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-notifications-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-notifications-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-notifications-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/notifdata/pgdata 

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: apiservice-secret
  namespace: agriroute
type: Opaque
stringData:
  TWILIO_ACCOUNT_SID: "ACba96a8ca5944d5719beacffd70ee42e7"
  TWILIO_AUTH_TOKEN: "91712b907e70cf32cc35f01b5f97b910"
  TWILIO_PHONE_NUMBER: "+18566198894"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-notifications-secret
  namespace: agriroute
type: Opaque
stringData:
  POSTGRES_USER: "agriroute"
  POSTGRES_PASSWORD: "agriroute2025"
  POSTGRES_DB: "geral"