apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: agriroute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
      nodeSelector:
        kubernetes.io/hostname: kub13
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: agriroute
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
  type: ClusterIP
