services:
  routing:
    build:
      context: .
    container_name: routing
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]
    ports:
      - "8006:8003"
    dns:
      - 8.8.8.8
      - 1.1.1.1