apiVersion: apps/v1
kind: Deployment
metadata:
  name: agriroute-payments
  namespace: agriroute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agriroute-payments
  template:
    metadata:
      labels:
        app: agriroute-payments
    spec:
      containers:
        - name: agriroute-payments
          image: registry.deti/agriroute/payment_service:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: db_password
            - name: DB_HOST
              value: payments-db 
---
apiVersion: v1
kind: Service
metadata:
  name: agriroute-payments
  namespace: agriroute
spec:
  selector:
    app: agriroute-payments
  ports:
    - port: 80
      targetPort: 8000
