apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-db
  namespace: agriroute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-db
  template:
    metadata:
      labels:
        app: payments-db
    spec:
      containers:
        - name: postgres
          image: registry.deti/agriroute/payments_db:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: db_password
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: payments-db
  namespace: agriroute
spec:
  selector:
    app: payments-db
  ports:
    - port: 5432
